#!/bin/bash

#specify export QSUB vars to shell script
#$ -V -R y -q parallel.q -N CQM

#execute script from current working directory 
#$ -cwd

#select parallel environment to run on 1 node
#$ -pe openmpi 1

#select max run-time
#$ -l h_rt=12:00:00

#number of cores (up to 6x number of nodes)
NUM_CORES=2

#name of parallel executable
EXEC=/usr/local/bin/castep.mpi

#check for seed
if [ -z "$1" ]
then
 echo "Please specify seed - e.g. qsub run_castep si2"
 exit
else

#set up temp directory in scratch
#if [ -e /scratch/${USER} ]
#then
# TMPDIR=/scratch/${USER}/${JOB_ID}
# mkdir $TMPDIR
#else
# mkdir /scratch/${USER}
# TMPDIR=/scratch/${USER}/${JOB_ID}
# mkdir $TMPDIR
#fi

#copy input to scratch
#cd $SGE_O_WORKDIR
#cp $1.* *.usp $TMPDIR 
#cd $TMPDIR

#run castep
mpirun -np $NUM_CORES $EXEC $1

echo ""
echo "Finished: "`date`
echo ""

#finally copy results back
#cp -f $1.* $SGE_O_WORKDIR


fi
