#!/bin/sh

# Collect -D & -m options as java arguments
command=java
while [ `echo $1 | egrep '^-D|^-m' | wc -l` != 0 ]; do
	command="$command $1"
	shift
done

# Find the path for jmol itself
jmol_path=`echo $0 | sed -e 's/jmol//g' `
if [ -f ./Jmol.jar ] ; then
  jarpath=./Jmol.jar
else
  echo Jmol.jar not found
  exit 1
fi
$command -Xmx512m -jar $jarpath $@
